'use client'

import { useEffect, useState } from "react"
import { forbidden, useRouter } from "next/navigation"
import { useAppDispatch, useAppSelector } from "@/lib/hooks"
import { resetState, selectCurrentUser, setCurrentUser } from "@/lib/appSlice"
import api from "../lib/apis"
import { v4 as uuid4 } from "uuid"

const SET_USER_ID_EVENT = "setUserIdEvent"
const USER_ID_KEY = "userId"
const USER_ID_AUTOGENERATED_KEY = "userIdAutoGenerated"

export function saveUserId(userId?: string, autogenerated: boolean = false) {
  console.log("Saving user ID", userId, autogenerated)
  if (!userId) {
    localStorage.setItem(USER_ID_KEY, "")
    localStorage.setItem(USER_ID_AUTOGENERATED_KEY, "")
  } else {
    localStorage.setItem(USER_ID_KEY, userId)
    localStorage.setItem(USER_ID_AUTOGENERATED_KEY, autogenerated ? "true" : "")
  }
  window.dispatchEvent(new Event(SET_USER_ID_EVENT))
}

export function getUserId() {
  if (!window) {
    console.error("No window???")
    // return {
    //   userId: "",
    //   autogenerated: false
    // }
  }
  const userId = {
    userId: localStorage.getItem(USER_ID_KEY) ?? "",
    autogenerated: Boolean(localStorage.getItem(USER_ID_AUTOGENERATED_KEY))
  }
  console.log("Got user ID", userId.userId, userId.autogenerated)
  return userId
}

export function initUserId() {
  const { userId } = getUserId()
  if (!userId) {
    saveUserId(uuid4(), true)
  }
}

export function useLogin() {
  const dispatch = useAppDispatch()
  const login = async (userId: string) => {
    try {
      const user = await api.getMe()
      if (user) {
        saveUserId(userId)
        dispatch(setCurrentUser(user))
        return true
      }
    } catch (e) {
      console.error(e)
    }
    saveUserId()
    return false
  }
  return login
}

export function useLogout() {
  const dispatch = useAppDispatch()
  const logout = async () => {
    saveUserId()
    dispatch(resetState())
  }
  return logout
}

export function useAuthenticated() {
  const [isAuthenticated, setIsAuthenticated] = useState<boolean | undefined>(undefined)
  const dispatch = useAppDispatch()

  async function handleSetUserIdEvent() {
    setIsAuthenticated(undefined)
    if (!await api.loginRequired()) {
      console.log("Login not required")
      setIsAuthenticated(true)
      return
    }
    const { userId, autogenerated } = getUserId()
    if (autogenerated) {
      setIsAuthenticated(true)
      dispatch(setCurrentUser({ id: userId, admin: false, active: true, attributes: {} }))
      return
    }
    try {
      const currentUser = await api.getMe()
      if (currentUser) {
        console.log("User ID valid")
        dispatch(setCurrentUser(currentUser))
        setIsAuthenticated(true)
        return
      }
    } catch { }
    console.log("User ID invalid")
    setIsAuthenticated(false)
    saveUserId()
  }

  useEffect(() => {
    initUserId()
    handleSetUserIdEvent()
    window.addEventListener(SET_USER_ID_EVENT, handleSetUserIdEvent)
    return () => {
      window.removeEventListener(SET_USER_ID_EVENT, handleSetUserIdEvent)
    }
  }, [])

  return isAuthenticated
}


interface AuthGuardProps {
  children: React.ReactNode,
  admin?: boolean,
  condition?: Promise<boolean>
}

export function AuthGuard({ children, admin, condition }: AuthGuardProps) {
  const isAuthed = useAuthenticated()
  const router = useRouter()
  const currentUser = useAppSelector(selectCurrentUser)
  const [conditionResult, setConditionResult] = useState<boolean | undefined>(condition ? undefined : true)

  useEffect(() => {
    (async () => {
      setConditionResult(undefined)
      setConditionResult(condition ? await condition : true)
    })()
  }, [isAuthed, router, currentUser, condition])

  if (isAuthed === undefined || conditionResult === undefined) {
    return null
  }

  if (!conditionResult || isAuthed === false || admin && (!currentUser || !currentUser.admin)) {
    forbidden()
  }

  return <>{children}</>
}