'use client'

import { forbidden } from "next/navigation"
import { useAppDispatch, useAppSelector } from "@/lib/hooks"
import { resetState, selectCurrentUser, setCurrentUser } from "@/lib/appSlice"
import api from "../lib/apis"
import { v4 as uuid4 } from "uuid"
import { UserRead } from "@/api"

// const SET_USER_ID_EVENT = "setUserIdEvent"
const USER_KEY = "userId"

export function saveUser(user?: UserRead) {
  console.log("Saving user", user)
  localStorage.setItem(USER_KEY, JSON.stringify(user))
  // window.dispatchEvent(new Event(SET_USER_ID_EVENT))
}

export function getSavedUser() {
  if (!localStorage) {
    return undefined
  }
  let user = undefined
  const json = localStorage.getItem(USER_KEY)
  if (json) {
    try {
      user = JSON.parse(json) as UserRead
    } catch {}
  }
  console.log("Got saved user", user)
  return user
}

export function initUser() {
  console.log("Initiating user")
  let user = getSavedUser()
  if (!user) {
    console.log("Autogenerating user")
    user = {id: uuid4(), attributes: {}, admin: false, autogenerated: true, active: true}
    saveUser(user)
  }
  return user
}

export function useLogin() {
  const dispatch = useAppDispatch()
  const currentUser = useAppSelector(selectCurrentUser)
  const login = async (userId: string) => {
    console.log("Logging in")
    try {
      api.setUserId(userId)
      const user = await api.getMe()
      if (user) {
        saveUser(user)
        dispatch(setCurrentUser(user))
        return true
      }
    } catch (e) {
      console.error(e)
    }
    console.log("Login unsuccessful")
    api.setUserId(currentUser?.id)
    return false
  }
  return login
}

export function useLogout() {
  const dispatch = useAppDispatch()
  const logout = async () => {
    saveUser()
    dispatch(resetState())
  }
  return logout
}

// export function useAuthenticated() {
//   const [isAuthenticated, setIsAuthenticated] = useState<boolean | undefined>(undefined)
//   const dispatch = useAppDispatch()

//   async function handleSetUserIdEvent() {
//     setIsAuthenticated(undefined)
//     const { userId, autogenerated } = getUserId()
//     if (autogenerated) {
//       setIsAuthenticated(true)
//       dispatch(setCurrentUser({ id: userId, admin: false, active: true, attributes: {}, autogenerated: true }))
//       return
//     }
//     try {
//       const currentUser = await api.getMe()
//       if (currentUser) {
//         console.log("User ID valid")
//         dispatch(setCurrentUser(currentUser))
//         setIsAuthenticated(true)
//         return
//       }
//     } catch { }
//     console.log("User ID invalid")
//     setIsAuthenticated(false)
//     saveUserId()
//   }

//   useEffect(() => {
//     initUserId()
//     handleSetUserIdEvent()
//     window.addEventListener(SET_USER_ID_EVENT, handleSetUserIdEvent)
//     return () => {
//       window.removeEventListener(SET_USER_ID_EVENT, handleSetUserIdEvent)
//     }
//   }, [])

//   return isAuthenticated
// }


interface AuthGuardProps {
  children: React.ReactNode,
  admin?: boolean,
  // condition?: Promise<boolean>
}

export function AuthGuard({ children, admin }: AuthGuardProps) {
  const dispatch = useAppDispatch()
  let currentUser = useAppSelector(selectCurrentUser)
  if (!currentUser) {
    currentUser = initUser()
    dispatch(setCurrentUser(currentUser))
  }
  api.setUserId(currentUser.id)

  // useEffect(() => {
  //   (async () => {
  //     setConditionResult(undefined)
  //     setConditionResult(condition ? await condition : true)
  //   })()
  // }, [isAuthed, router, currentUser, condition])
  

  if (admin && (!currentUser || !currentUser.admin)) {
    forbidden()
  }

  return <>{children}</>
}