'use client'

import {
  Navbar as HeroUINavbar,
  NavbarContent,
  NavbarMenuToggle,
  NavbarBrand,
  NavbarItem,
} from "@heroui/react";
import { Link } from "@heroui/react";
import { link as linkStyles } from "@heroui/react";
import NextLink from "next/link";
import clsx from "clsx";

import { siteConfig } from "@/config/site";
import { ThemeSwitch } from "@/components/theme-switch";
import {
  GithubIcon,
  Logo,
} from "@/components/icons";

import { Button, Code, Tooltip } from "@heroui/react";
import { useLogout } from "./auth";
import { useRouter } from "next/navigation";
import { useAppSelector } from "@/lib/hooks";
import { selectState } from "@/lib/appSlice";

export const Navbar = () => {

  const router = useRouter()
  const logout = useLogout()
  const currentUser = useAppSelector(selectState).currentUser

  return (
    <HeroUINavbar isBordered height={"4rem"} maxWidth="xl" position="sticky">
      <NavbarContent className="basis-1/5 sm:basis-full" justify="start">
        <NavbarBrand as="li" className="gap-3 max-w-fit">
          <NextLink className="flex justify-start items-center gap-1" href="/">
            <Logo />
            <p className="font-bold text-inherit">LLManipulate</p>
          </NextLink>
        </NavbarBrand>
        <ul className="hidden lg:flex gap-4 justify-start ml-2">
          {siteConfig.navItems.map((item) => (
            <NavbarItem key={item.href}>
              <NextLink
                className={clsx(
                  linkStyles({ color: "foreground" }),
                  "data-[active=true]:text-primary data-[active=true]:font-medium",
                )}
                color="primary"
                href={item.href}
              >
                {item.label}
              </NextLink>
            </NavbarItem>
          ))}
        </ul>
      </NavbarContent>

      <NavbarContent
        className="hidden sm:flex basis-1/5 sm:basis-full"
        justify="end"
      >
        <NavbarItem className="hidden sm:flex gap-2">
          <Link isExternal aria-label="Github" href={siteConfig.links.github}>
            <GithubIcon className="text-default-500" />
          </Link>
          <ThemeSwitch />
        </NavbarItem>
        <Tooltip content={<Code>{JSON.stringify(currentUser) ?? "null"}</Code>}>
          {currentUser && !currentUser.autogenerated
            ? <Button
              variant="flat"
              onPress={async () => {
                await logout()
                router.push("/")
              }}
            >
              Logout
            </Button>
            : <Button variant="flat" onPress={() => router.push("/login")}>Login</Button>
          }
        </Tooltip>
        {currentUser?.admin && <div>
          Admin
        </div>}
      </NavbarContent>

      <NavbarContent className="sm:hidden basis-1 pl-4" justify="end">
        <Link isExternal aria-label="Github" href={siteConfig.links.github}>
          <GithubIcon className="text-default-500" />
        </Link>
        <ThemeSwitch />
        <NavbarMenuToggle />
      </NavbarContent>

    </HeroUINavbar>
  );
}