/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Participant } from '../models/Participant';
import { Translations } from '../models/Translations';
import { HttpFile } from '../http/http';

export class Chat {
    'id': string;
    'label'?: Translations | null;
    'optional'?: boolean;
    'type'?: ChatTypeEnum;
    'participants'?: Array<Participant>;
    'order'?: Array<string> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "Translations",
            "format": ""
        },
        {
            "name": "optional",
            "baseName": "optional",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ChatTypeEnum",
            "format": ""
        },
        {
            "name": "participants",
            "baseName": "participants",
            "type": "Array<Participant>",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Chat.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ChatTypeEnum {
    Chat = 'chat'
}

