/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChatMessage } from '../models/ChatMessage';
import { HttpFile } from '../http/http';

export class ChatHistory {
    'id': string;
    'messages': Array<ChatMessage>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "messages",
            "baseName": "messages",
            "type": "Array<ChatMessage>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChatHistory.attributeTypeMap;
    }

    public constructor() {
    }
}
