/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComponentGroupComponentsInner } from '../models/ComponentGroupComponentsInner';
import { Translations } from '../models/Translations';
import { HttpFile } from '../http/http';

export class ComponentGroup {
    'label'?: Translations | null;
    'components': Array<ComponentGroupComponentsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "label",
            "baseName": "label",
            "type": "Translations",
            "format": ""
        },
        {
            "name": "components",
            "baseName": "components",
            "type": "Array<ComponentGroupComponentsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ComponentGroup.attributeTypeMap;
    }

    public constructor() {
    }
}
