/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Translations } from '../models/Translations';
import { HttpFile } from '../http/http';

export class FreeText {
    'id': string;
    'label': Translations | null;
    'optional'?: boolean;
    'type'?: FreeTextTypeEnum;
    'regex'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "Translations",
            "format": ""
        },
        {
            "name": "optional",
            "baseName": "optional",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "FreeTextTypeEnum",
            "format": ""
        },
        {
            "name": "regex",
            "baseName": "regex",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FreeText.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum FreeTextTypeEnum {
    FreeText = 'free_text'
}

