/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Id } from '../models/Id';
import { RootModelUnionTranslationsStr } from '../models/RootModelUnionTranslationsStr';
import { HttpFile } from '../http/http';

export class MultiChoice {
    'id': Id;
    'label': RootModelUnionTranslationsStr;
    'optional'?: boolean;
    'choices': Array<RootModelUnionTranslationsStr>;
    /**
    * If `true`, choices are displayed in a random order to the user
    */
    'shuffle'?: boolean;
    'type'?: MultiChoiceTypeEnum;
    'minChoices'?: number;
    'maxChoices'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "Id",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "RootModelUnionTranslationsStr",
            "format": ""
        },
        {
            "name": "optional",
            "baseName": "optional",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "choices",
            "baseName": "choices",
            "type": "Array<RootModelUnionTranslationsStr>",
            "format": ""
        },
        {
            "name": "shuffle",
            "baseName": "shuffle",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "MultiChoiceTypeEnum",
            "format": ""
        },
        {
            "name": "minChoices",
            "baseName": "min_choices",
            "type": "number",
            "format": ""
        },
        {
            "name": "maxChoices",
            "baseName": "max_choices",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MultiChoice.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum MultiChoiceTypeEnum {
    MultiChoice = 'multi_choice'
}

