/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Id } from '../models/Id';
import { RootModelUnionTranslationsStr } from '../models/RootModelUnionTranslationsStr';
import { HttpFile } from '../http/http';

export class Slider {
    'id': Id;
    'label': RootModelUnionTranslationsStr;
    'optional'?: boolean;
    'type'?: SliderTypeEnum;
    'steps': number;
    'labels'?: Array<RootModelUnionTranslationsStr> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "Id",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "RootModelUnionTranslationsStr",
            "format": ""
        },
        {
            "name": "optional",
            "baseName": "optional",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "SliderTypeEnum",
            "format": ""
        },
        {
            "name": "steps",
            "baseName": "steps",
            "type": "number",
            "format": ""
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "Array<RootModelUnionTranslationsStr>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Slider.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum SliderTypeEnum {
    Slider = 'slider'
}

