/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ResponseValue } from '../models/ResponseValue';
import { HttpFile } from '../http/http';

export class TaskResponseRead {
    'task': string;
    'draft'?: boolean;
    'response': { [key: string]: ResponseValue; };

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "task",
            "baseName": "task",
            "type": "string",
            "format": "uuid4"
        },
        {
            "name": "draft",
            "baseName": "draft",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "response",
            "baseName": "response",
            "type": "{ [key: string]: ResponseValue; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskResponseRead.attributeTypeMap;
    }

    public constructor() {
    }
}
