/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TaskConfig } from '../models/TaskConfig';
import { UserRead } from '../models/UserRead';
import { HttpFile } from '../http/http';

export class TaskRead {
    'id'?: string;
    'config': TaskConfig;
    '_public'?: boolean;
    'creator': UserRead;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid4"
        },
        {
            "name": "config",
            "baseName": "config",
            "type": "TaskConfig",
            "format": ""
        },
        {
            "name": "_public",
            "baseName": "public",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "creator",
            "baseName": "creator",
            "type": "UserRead",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskRead.attributeTypeMap;
    }

    public constructor() {
    }
}
