/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ResponseValue } from '../models/ResponseValue';
import { HttpFile } from '../http/http';

export class TaskResponse {
    'task': string;
    'draft'?: boolean;
    'response': { [key: string]: ResponseValue; };
    'updatedTimestamp'?: Date;
    'createdTimestamp'?: Date;
    'user': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "task",
            "baseName": "task",
            "type": "string",
            "format": "uuid4"
        },
        {
            "name": "draft",
            "baseName": "draft",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "response",
            "baseName": "response",
            "type": "{ [key: string]: ResponseValue; }",
            "format": ""
        },
        {
            "name": "updatedTimestamp",
            "baseName": "updated_timestamp",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createdTimestamp",
            "baseName": "created_timestamp",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "string",
            "format": "uuid4"
        }    ];

    static getAttributeTypeMap() {
        return TaskResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
