/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UserCreate {
    'email': string;
    'password': string;
    'isActive'?: boolean | null;
    'isSuperuser'?: boolean | null;
    'isVerified'?: boolean | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": "email"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        },
        {
            "name": "isActive",
            "baseName": "is_active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isSuperuser",
            "baseName": "is_superuser",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isVerified",
            "baseName": "is_verified",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserCreate.attributeTypeMap;
    }

    public constructor() {
    }
}
