// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetChatData, GetChatResponse, GetChatError, GetAllUsersData, GetAllUsersResponse, CreateUserData, CreateUserResponse, CreateUserError, GetMeData, GetMeResponse, LoginRequiredData, LoginRequiredResponse, GetUserData, GetUserResponse, GetUserError, GetAllUsersResponsesData, GetAllUsersResponsesResponse, GetMyTasksData, GetMyTasksResponse, GetAllTasksData, GetAllTasksResponse, GetTaskData, GetTaskResponse, GetTaskError, GetSampleTaskData, GetSampleTaskResponse, GetTaskResponsesData, GetTaskResponsesResponse, GetTaskResponsesError, CreateTaskResponseData, CreateTaskResponseResponse, CreateTaskResponseError, GetResponsesData } from './types.gen';
import { getChatResponseTransformer, getAllUsersResponsesResponseTransformer, getTaskResponsesResponseTransformer, createTaskResponseResponseTransformer } from './transformers.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Chat
 */
export const getChat = <ThrowOnError extends boolean = false>(options: Options<GetChatData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetChatResponse, GetChatError, ThrowOnError>({
        responseTransformer: getChatResponseTransformer,
        url: '/chats/{chat_id}',
        ...options
    });
};

/**
 * Get All Users
 */
export const getAllUsers = <ThrowOnError extends boolean = false>(options?: Options<GetAllUsersData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllUsersResponse, unknown, ThrowOnError>({
        url: '/users',
        ...options
    });
};

/**
 * Create User
 * Creates a new participant. Requires an admin's user_id for authentication.
 */
export const createUser = <ThrowOnError extends boolean = false>(options: Options<CreateUserData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<CreateUserResponse, CreateUserError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Me
 */
export const getMe = <ThrowOnError extends boolean = false>(options?: Options<GetMeData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetMeResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/me',
        ...options
    });
};

/**
 * Login Required
 */
export const loginRequired = <ThrowOnError extends boolean = false>(options?: Options<LoginRequiredData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<LoginRequiredResponse, unknown, ThrowOnError>({
        url: '/users/login-required',
        ...options
    });
};

/**
 * Get User
 */
export const getUser = <ThrowOnError extends boolean = false>(options: Options<GetUserData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetUserResponse, GetUserError, ThrowOnError>({
        url: '/users/{user_id}',
        ...options
    });
};

/**
 * Get All Users Responses
 */
export const getAllUsersResponses = <ThrowOnError extends boolean = false>(options?: Options<GetAllUsersResponsesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllUsersResponsesResponse, unknown, ThrowOnError>({
        responseTransformer: getAllUsersResponsesResponseTransformer,
        url: '/users/users_responses',
        ...options
    });
};

/**
 * Get My Tasks
 */
export const getMyTasks = <ThrowOnError extends boolean = false>(options?: Options<GetMyTasksData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetMyTasksResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/me/tasks',
        ...options
    });
};

/**
 * Get All Tasks
 */
export const getAllTasks = <ThrowOnError extends boolean = false>(options?: Options<GetAllTasksData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllTasksResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/tasks/',
        ...options
    });
};

/**
 * Get Task
 */
export const getTask = <ThrowOnError extends boolean = false>(options: Options<GetTaskData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetTaskResponse, GetTaskError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/tasks/{task_id}',
        ...options
    });
};

/**
 * Get Sample Task
 */
export const getSampleTask = <ThrowOnError extends boolean = false>(options?: Options<GetSampleTaskData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetSampleTaskResponse, unknown, ThrowOnError>({
        url: '/tasks/sample',
        ...options
    });
};

/**
 * Get Task Responses
 */
export const getTaskResponses = <ThrowOnError extends boolean = false>(options: Options<GetTaskResponsesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetTaskResponsesResponse, GetTaskResponsesError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseTransformer: getTaskResponsesResponseTransformer,
        url: '/tasks/{task_id}/responses',
        ...options
    });
};

/**
 * Create Task Response
 */
export const createTaskResponse = <ThrowOnError extends boolean = false>(options: Options<CreateTaskResponseData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateTaskResponseResponse, CreateTaskResponseError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseTransformer: createTaskResponseResponseTransformer,
        url: '/tasks/{task_id}/response',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Responses
 */
export const getResponses = <ThrowOnError extends boolean = false>(options?: Options<GetResponsesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        url: '/responses',
        ...options
    });
};