// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { ExampleSendData, ExampleSendError, ExampleReceiveData, ExampleReceiveError, ExampleChatMessageReadData, ExampleChatMessageReadError, GetUsersData, GetUsersResponse, UpsertUserData, UpsertUserResponse, UpsertUserError, GetMeData, GetMeResponse, GetUserData, GetUserResponse, GetUserError, GetUserResponsesData, GetUserResponsesResponse, GetUserResponsesError, GetMyTasksData, GetMyTasksResponse, GetTasksData, GetTasksResponse, CreateTaskData, CreateTaskResponse, CreateTaskError, DeleteTaskData, DeleteTaskError, GetTaskData, GetTaskResponse, GetTaskError, GetSampleTaskData, GetSampleTaskResponse, GetTaskResponsesData, GetTaskResponsesResponse, GetTaskResponsesError, GetTaskChatsData, GetTaskChatsResponse, GetTaskChatsError, CreateTaskResponseData, CreateTaskResponseResponse, CreateTaskResponseError, GetTaskParticipantsData, GetTaskParticipantsResponse, GetTaskParticipantsError, GetResponsesData, GetResponsesResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';
import { getUserResponsesResponseTransformer, getTaskResponsesResponseTransformer, getTaskChatsResponseTransformer, createTaskResponseResponseTransformer, getResponsesResponseTransformer } from './transformers.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Example Send
 */
export const exampleSend = <ThrowOnError extends boolean = false>(options: Options<ExampleSendData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, ExampleSendError, ThrowOnError>({
        url: '/chat/example/send',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Example Receive
 */
export const exampleReceive = <ThrowOnError extends boolean = false>(options: Options<ExampleReceiveData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, ExampleReceiveError, ThrowOnError>({
        url: '/chat/example/receive',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Example Chat Message Read
 */
export const exampleChatMessageRead = <ThrowOnError extends boolean = false>(options: Options<ExampleChatMessageReadData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, ExampleChatMessageReadError, ThrowOnError>({
        url: '/chat/example/chat-message-read',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Users
 */
export const getUsers = <ThrowOnError extends boolean = false>(options?: Options<GetUsersData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetUsersResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users',
        ...options
    });
};

/**
 * Upsert User
 * Create or update a new user. Requires an admin's user_id for authentication.
 */
export const upsertUser = <ThrowOnError extends boolean = false>(options: Options<UpsertUserData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UpsertUserResponse, UpsertUserError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Me
 */
export const getMe = <ThrowOnError extends boolean = false>(options?: Options<GetMeData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetMeResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/me',
        ...options
    });
};

/**
 * Get User
 */
export const getUser = <ThrowOnError extends boolean = false>(options: Options<GetUserData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetUserResponse, GetUserError, ThrowOnError>({
        url: '/users/{user_id}',
        ...options
    });
};

/**
 * Get User Responses
 */
export const getUserResponses = <ThrowOnError extends boolean = false>(options: Options<GetUserResponsesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetUserResponsesResponse, GetUserResponsesError, ThrowOnError>({
        responseTransformer: getUserResponsesResponseTransformer,
        url: '/users/{user_id}/responses',
        ...options
    });
};

/**
 * Get My Tasks
 */
export const getMyTasks = <ThrowOnError extends boolean = false>(options?: Options<GetMyTasksData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetMyTasksResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/me/tasks',
        ...options
    });
};

/**
 * Get Tasks
 */
export const getTasks = <ThrowOnError extends boolean = false>(options?: Options<GetTasksData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetTasksResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/tasks/',
        ...options
    });
};

/**
 * Create Task
 */
export const createTask = <ThrowOnError extends boolean = false>(options: Options<CreateTaskData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateTaskResponse, CreateTaskError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/tasks/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete Task
 */
export const deleteTask = <ThrowOnError extends boolean = false>(options: Options<DeleteTaskData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<unknown, DeleteTaskError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/tasks/{task_id}',
        ...options
    });
};

/**
 * Get Task
 */
export const getTask = <ThrowOnError extends boolean = false>(options: Options<GetTaskData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetTaskResponse, GetTaskError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/tasks/{task_id}',
        ...options
    });
};

/**
 * Get Sample Task
 */
export const getSampleTask = <ThrowOnError extends boolean = false>(options?: Options<GetSampleTaskData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetSampleTaskResponse, unknown, ThrowOnError>({
        url: '/tasks/sample',
        ...options
    });
};

/**
 * Get Task Responses
 */
export const getTaskResponses = <ThrowOnError extends boolean = false>(options: Options<GetTaskResponsesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetTaskResponsesResponse, GetTaskResponsesError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseTransformer: getTaskResponsesResponseTransformer,
        url: '/tasks/{task_id}/responses',
        ...options
    });
};

/**
 * Get Task Chats
 */
export const getTaskChats = <ThrowOnError extends boolean = false>(options: Options<GetTaskChatsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetTaskChatsResponse, GetTaskChatsError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseTransformer: getTaskChatsResponseTransformer,
        url: '/tasks/{task_id}/chats',
        ...options
    });
};

/**
 * Create Task Response
 */
export const createTaskResponse = <ThrowOnError extends boolean = false>(options: Options<CreateTaskResponseData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateTaskResponseResponse, CreateTaskResponseError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseTransformer: createTaskResponseResponseTransformer,
        url: '/tasks/{task_id}/response',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Task Participants
 */
export const getTaskParticipants = <ThrowOnError extends boolean = false>(options: Options<GetTaskParticipantsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetTaskParticipantsResponse, GetTaskParticipantsError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/tasks/{task_id}/participants',
        ...options
    });
};

/**
 * Get Responses
 */
export const getResponses = <ThrowOnError extends boolean = false>(options?: Options<GetResponsesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetResponsesResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseTransformer: getResponsesResponseTransformer,
        url: '/responses',
        ...options
    });
};