// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, urlSearchParamsBodySerializer } from '@hey-api/client-fetch';
import type { AuthAuthLoginData, AuthAuthLoginResponse, AuthAuthLoginError, AuthAuthLogoutData, RegisterRegisterData, RegisterRegisterResponse, RegisterRegisterError, ResetForgotPasswordData, ResetForgotPasswordError, ResetResetPasswordData, ResetResetPasswordError, VerifyRequestTokenData, VerifyRequestTokenError, VerifyVerifyData, VerifyVerifyResponse, VerifyVerifyError, UsersCurrentUserData, UsersCurrentUserResponse, UsersPatchCurrentUserData, UsersPatchCurrentUserResponse, UsersPatchCurrentUserError, UsersDeleteUserData, UsersDeleteUserResponse, UsersDeleteUserError, UsersUserData, UsersUserResponse, UsersUserError, UsersPatchUserData, UsersPatchUserResponse, UsersPatchUserError, GetResponsesData, GetChatData, GetChatResponse, GetChatError, GetAllUsersData, GetAllUsersResponse, CreateUserData, CreateUserResponse, CreateUserError, GetUserData, GetUserResponse, GetUserError, GetAllUsersResponsesData, GetAllUsersResponsesResponse, GetMyTasksData, GetMyTasksResponse, GetAllTasksData, GetAllTasksResponse, GetTaskData, GetTaskResponse, GetTaskError, GetSampleTaskData, GetSampleTaskResponse, GetTaskResponseData, GetTaskResponseResponse, GetTaskResponseError, CreateTaskResponseData, CreateTaskResponseResponse, CreateTaskResponseError } from './types.gen';
import { client as _heyApiClient } from './client.gen';
import { getChatResponseTransformer, getAllUsersResponsesResponseTransformer, getTaskResponseResponseTransformer, createTaskResponseResponseTransformer } from './transformers.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Auth:Auth.Login
 */
export const authAuthLogin = <ThrowOnError extends boolean = false>(options: Options<AuthAuthLoginData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AuthAuthLoginResponse, AuthAuthLoginError, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options?.headers
        }
    });
};

/**
 * Auth:Auth.Logout
 */
export const authAuthLogout = <ThrowOnError extends boolean = false>(options?: Options<AuthAuthLogoutData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/auth/logout',
        ...options
    });
};

/**
 * Register:Register
 */
export const registerRegister = <ThrowOnError extends boolean = false>(options: Options<RegisterRegisterData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<RegisterRegisterResponse, RegisterRegisterError, ThrowOnError>({
        url: '/auth/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Reset:Forgot Password
 */
export const resetForgotPassword = <ThrowOnError extends boolean = false>(options: Options<ResetForgotPasswordData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, ResetForgotPasswordError, ThrowOnError>({
        url: '/auth/forgot-password',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Reset:Reset Password
 */
export const resetResetPassword = <ThrowOnError extends boolean = false>(options: Options<ResetResetPasswordData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, ResetResetPasswordError, ThrowOnError>({
        url: '/auth/reset-password',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Verify:Request-Token
 */
export const verifyRequestToken = <ThrowOnError extends boolean = false>(options: Options<VerifyRequestTokenData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, VerifyRequestTokenError, ThrowOnError>({
        url: '/auth/request-verify-token',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Verify:Verify
 */
export const verifyVerify = <ThrowOnError extends boolean = false>(options: Options<VerifyVerifyData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<VerifyVerifyResponse, VerifyVerifyError, ThrowOnError>({
        url: '/auth/verify',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Users:Current User
 */
export const usersCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<UsersCurrentUserData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<UsersCurrentUserResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/me',
        ...options
    });
};

/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUser = <ThrowOnError extends boolean = false>(options: Options<UsersPatchCurrentUserData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UsersPatchCurrentUserResponse, UsersPatchCurrentUserError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/me',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Users:Delete User
 */
export const usersDeleteUser = <ThrowOnError extends boolean = false>(options: Options<UsersDeleteUserData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<UsersDeleteUserResponse, UsersDeleteUserError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/{id}',
        ...options
    });
};

/**
 * Users:User
 */
export const usersUser = <ThrowOnError extends boolean = false>(options: Options<UsersUserData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<UsersUserResponse, UsersUserError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/{id}',
        ...options
    });
};

/**
 * Users:Patch User
 */
export const usersPatchUser = <ThrowOnError extends boolean = false>(options: Options<UsersPatchUserData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UsersPatchUserResponse, UsersPatchUserError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Responses
 */
export const getResponses = <ThrowOnError extends boolean = false>(options?: Options<GetResponsesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        url: '/responses',
        ...options
    });
};

/**
 * Get Chat
 */
export const getChat = <ThrowOnError extends boolean = false>(options: Options<GetChatData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetChatResponse, GetChatError, ThrowOnError>({
        responseTransformer: getChatResponseTransformer,
        url: '/chats/{chat_id}',
        ...options
    });
};

/**
 * Get All Users
 */
export const getAllUsers = <ThrowOnError extends boolean = false>(options?: Options<GetAllUsersData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllUsersResponse, unknown, ThrowOnError>({
        url: '/users',
        ...options
    });
};

/**
 * Create User
 * Creates a new non-admin user. Requires an admin's user_id for authentication.
 */
export const createUser = <ThrowOnError extends boolean = false>(options: Options<CreateUserData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<CreateUserResponse, CreateUserError, ThrowOnError>({
        url: '/users',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get User
 */
export const getUser = <ThrowOnError extends boolean = false>(options: Options<GetUserData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetUserResponse, GetUserError, ThrowOnError>({
        url: '/users/{user_id}',
        ...options
    });
};

/**
 * Get All Users Responses
 */
export const getAllUsersResponses = <ThrowOnError extends boolean = false>(options?: Options<GetAllUsersResponsesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllUsersResponsesResponse, unknown, ThrowOnError>({
        responseTransformer: getAllUsersResponsesResponseTransformer,
        url: '/users/users_responses',
        ...options
    });
};

/**
 * Get My Tasks
 */
export const getMyTasks = <ThrowOnError extends boolean = false>(options?: Options<GetMyTasksData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetMyTasksResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/me/tasks',
        ...options
    });
};

/**
 * Get All Tasks
 */
export const getAllTasks = <ThrowOnError extends boolean = false>(options?: Options<GetAllTasksData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllTasksResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/tasks/',
        ...options
    });
};

/**
 * Get Task
 */
export const getTask = <ThrowOnError extends boolean = false>(options: Options<GetTaskData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetTaskResponse, GetTaskError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/tasks/{task_id}',
        ...options
    });
};

/**
 * Get Sample Task
 */
export const getSampleTask = <ThrowOnError extends boolean = false>(options?: Options<GetSampleTaskData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetSampleTaskResponse, unknown, ThrowOnError>({
        url: '/tasks/sample',
        ...options
    });
};

/**
 * Get Task Response
 */
export const getTaskResponse = <ThrowOnError extends boolean = false>(options: Options<GetTaskResponseData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetTaskResponseResponse, GetTaskResponseError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseTransformer: getTaskResponseResponseTransformer,
        url: '/tasks/{task_id}/response',
        ...options
    });
};

/**
 * Create Task Response
 */
export const createTaskResponse = <ThrowOnError extends boolean = false>(options: Options<CreateTaskResponseData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateTaskResponseResponse, CreateTaskResponseError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        responseTransformer: createTaskResponseResponseTransformer,
        url: '/tasks/{task_id}/response',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};