// This file is auto-generated by @hey-api/openapi-ts

import type { GetUserResponsesResponse, GetTaskResponsesResponse, GetTaskChatsResponse, CreateTaskResponseResponse, GetResponsesResponse } from './types.gen';

const taskResponseSchemaResponseTransformer = (data: any) => {
    if (data.created_timestamp) {
        data.created_timestamp = new Date(data.created_timestamp);
    }
    return data;
};

export const getUserResponsesResponseTransformer = async (data: any): Promise<GetUserResponsesResponse> => {
    data = data.map((item: any) => {
        return taskResponseSchemaResponseTransformer(item);
    });
    return data;
};

const taskResponseReadSchemaResponseTransformer = (data: any) => {
    if (data.created_timestamp) {
        data.created_timestamp = new Date(data.created_timestamp);
    }
    return data;
};

export const getTaskResponsesResponseTransformer = async (data: any): Promise<GetTaskResponsesResponse> => {
    data = data.map((item: any) => {
        return taskResponseReadSchemaResponseTransformer(item);
    });
    return data;
};

const chatMessageReadAdminSchemaResponseTransformer = (data: any) => {
    data.timestamp = new Date(data.timestamp);
    return data;
};

const chatReadAdminSchemaResponseTransformer = (data: any) => {
    data.messages = data.messages.map((item: any) => {
        return chatMessageReadAdminSchemaResponseTransformer(item);
    });
    return data;
};

export const getTaskChatsResponseTransformer = async (data: any): Promise<GetTaskChatsResponse> => {
    data = data.map((item: any) => {
        return chatReadAdminSchemaResponseTransformer(item);
    });
    return data;
};

export const createTaskResponseResponseTransformer = async (data: any): Promise<CreateTaskResponseResponse> => {
    data = taskResponseReadSchemaResponseTransformer(data);
    return data;
};

export const getResponsesResponseTransformer = async (data: any): Promise<GetResponsesResponse> => {
    data = data.map((item: any) => {
        return taskResponseReadSchemaResponseTransformer(item);
    });
    return data;
};