// This file is auto-generated by @hey-api/openapi-ts

export type AgentConfig = {
    /**
     * Similar to component ID, must be unique within this task, used to correlate chat messages with the agent that produced it.
     */
    id: string;
    /**
     * The name that will be displayed in chat, leave empty to make the agent look like a human user
     */
    display_name: string | null;
    model_name?: string;
    endpoint?: string;
    api_key?: string;
    attributes?: {
        [key: string]: unknown;
    };
    base_prompt?: string;
    prompt?: string;
};

export type ChatConfig = {
    /**
     * An ID unique within this task, used to correlate a component with its response
     */
    id: string;
    label?: Translations | null;
    optional?: boolean;
    type?: 'chat';
    agents?: Array<AgentConfig>;
    /**
     * Order of conversation, required if any agents are participating in the chat. Elements of this list are either an integer indicating the index (starting from 0) of the agent in the list `agents`, or the string 'human' to indicate a human's turn
     */
    order?: Array<number | 'human'> | null;
    min_messages?: number;
    max_messages?: number;
    /**
     * Number of humans per chat, leave None for no limit
     */
    humans_required?: number | null;
};

export type ChatMessageRead = {
    id: string;
    message: string;
    timestamp: Date;
    sender: string;
    chat_id: string;
};

export type ChatParticipantRead = {
    name: string;
    active: boolean;
    typing: boolean;
};

export type ComponentGroupInput = {
    /**
     * The number of columns used to display the children of this component
     */
    columns?: number;
    label?: Translations | null;
    components: Array<SingleChoice | MultiChoice | Slider | FreeText | ChatConfig>;
};

export type ComponentGroupOutput = {
    /**
     * The number of columns used to display the children of this component
     */
    columns?: number;
    label?: Translations | null;
    components: Array<SingleChoice | MultiChoice | Slider | FreeText | ChatConfig>;
};

export type ErrorResponse = {
    detail: string;
};

export type FreeText = {
    /**
     * An ID unique within this task, used to correlate a component with its response
     */
    id: string;
    label?: Translations | null;
    optional?: boolean;
    type?: 'free_text';
    /**
     * The regular expression pattern that the user's input must match. `null` performs no matching.
     */
    regex?: string | null;
    /**
     * Prompt to be shown if the regex does not match
     */
    regex_prompt?: string | null;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type LoginRequired = {
    login_required: boolean;
};

export type MultiChoice = {
    /**
     * An ID unique within this task, used to correlate a component with its response
     */
    id: string;
    label?: Translations | null;
    optional?: boolean;
    choices: Array<Translations>;
    /**
     * If `true`, choices are displayed in a random order to the user
     */
    shuffle?: boolean;
    type?: 'multi_choice';
    min_choices?: number;
    max_choices?: number;
};

/**
 * ✅ Schema for creating a chat room.
 */
export type RoomConfig = {
    all_users: boolean;
    order?: Array<string>;
};

export type RootModelInt = number;

export type RootModelListInt = Array<number>;

export type RootModelStr = string;

export type SingleChoice = {
    /**
     * An ID unique within this task, used to correlate a component with its response
     */
    id: string;
    label?: Translations | null;
    optional?: boolean;
    choices: Array<Translations>;
    /**
     * If `true`, choices are displayed in a random order to the user
     */
    shuffle?: boolean;
    type?: 'single_choice';
};

export type Slider = {
    /**
     * An ID unique within this task, used to correlate a component with its response
     */
    id: string;
    label?: Translations | null;
    optional?: boolean;
    type?: 'slider';
    steps: number;
    labels?: Array<Translations> | null;
};

export type TaskConfigInput = {
    name: Translations;
    description?: Translations | null;
    pages: Array<TaskPageInput>;
    public: boolean;
};

export type TaskConfigOutput = {
    name: Translations;
    description?: Translations | null;
    pages: Array<TaskPageOutput>;
    public: boolean;
};

export type TaskCreate = {
    config: TaskConfigInput;
};

export type TaskPageInput = {
    /**
     * The number of columns used to display the component groups
     */
    columns?: number;
    label?: Translations | string | null;
    component_groups: Array<ComponentGroupInput>;
};

export type TaskPageOutput = {
    /**
     * The number of columns used to display the component groups
     */
    columns?: number;
    label?: Translations | string | null;
    component_groups: Array<ComponentGroupOutput>;
};

export type TaskParticipantRead = {
    task_id: string;
    user_id: string;
    completed: boolean;
};

export type TaskRead = {
    config: TaskConfigOutput;
    id: string;
};

export type TaskReadParticipant = {
    config: TaskConfigOutput;
    id: string;
    completed: boolean;
};

export type TaskResponse = {
    response: {
        [key: string]: RootModelInt | RootModelListInt | RootModelStr;
    };
    created_timestamp?: Date;
    task: string;
    user_id: string;
};

export type TaskResponseCreate = {
    response: {
        [key: string]: RootModelInt | RootModelListInt | RootModelStr;
    };
};

export type TaskResponseRead = {
    response: {
        [key: string]: RootModelInt | RootModelListInt | RootModelStr;
    };
    created_timestamp?: Date;
    task: string;
    user_id: string;
};

export type Translations = {
    languages: {
        [key: string]: unknown;
    };
    /**
     * Default language to display. Must must be in `languages`. Will display an arbitrary language if left `null`.
     */
    default?: string | null;
};

export type User = {
    id?: string;
    attributes?: {
        [key: string]: unknown;
    };
    admin?: boolean;
    /**
     * Whether this user is allowed to login and submit responses
     */
    active?: boolean;
    autogenerated?: boolean;
};

export type UserRead = {
    id: string;
    attributes: {
        [key: string]: unknown;
    };
    admin: boolean;
    /**
     * Whether this user is allowed to login and submit responses
     */
    active: boolean;
};

export type UserUpsert = {
    id?: string | null;
    attributes?: {
        [key: string]: unknown;
    } | null;
    /**
     * Whether this user is allowed to login and submit responses
     */
    active?: boolean | null;
    /**
     * Tasks to add this user to
     */
    tasks_add?: Array<string>;
    /**
     * Tasks tasks to remove this user from
     */
    tasks_remove?: Array<string>;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type WebsocketReceive = {
    user_id: string;
    chat_id: string;
    typing: boolean;
    message: string;
};

export type WebsocketSend = {
    chat_id?: string;
    turn?: string;
    messages?: Array<ChatMessageRead>;
    me?: string;
    participants?: Array<ChatParticipantRead>;
    error?: string;
};

export type CreateRoomData = {
    body: RoomConfig;
    path?: never;
    query?: never;
    url: '/chat/create_room';
};

export type CreateRoomErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRoomError = CreateRoomErrors[keyof CreateRoomErrors];

export type CreateRoomResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExampleSendData = {
    body: WebsocketSend;
    path?: never;
    query?: never;
    url: '/chat/example/send';
};

export type ExampleSendErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExampleSendError = ExampleSendErrors[keyof ExampleSendErrors];

export type ExampleSendResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExampleReceiveData = {
    body: WebsocketReceive;
    path?: never;
    query?: never;
    url: '/chat/example/receive';
};

export type ExampleReceiveErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExampleReceiveError = ExampleReceiveErrors[keyof ExampleReceiveErrors];

export type ExampleReceiveResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type GetUsersResponses = {
    /**
     * Successful Response
     */
    200: Array<UserRead>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type UpsertUserData = {
    body: UserUpsert;
    path?: never;
    query?: never;
    url: '/users';
};

export type UpsertUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpsertUserError = UpsertUserErrors[keyof UpsertUserErrors];

export type UpsertUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UpsertUserResponse = UpsertUserResponses[keyof UpsertUserResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetMeResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type LoginRequiredData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/login-required';
};

export type LoginRequiredResponses = {
    /**
     * Successful Response
     */
    200: LoginRequired;
};

export type LoginRequiredResponse = LoginRequiredResponses[keyof LoginRequiredResponses];

export type GetUserData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type GetUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type GetUserResponsesData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}/responses';
};

export type GetUserResponsesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserResponsesError = GetUserResponsesErrors[keyof GetUserResponsesErrors];

export type GetUserResponsesResponses = {
    /**
     * Successful Response
     */
    200: Array<TaskResponse>;
};

export type GetUserResponsesResponse = GetUserResponsesResponses[keyof GetUserResponsesResponses];

export type GetMyTasksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/tasks';
};

export type GetMyTasksResponses = {
    /**
     * Successful Response
     */
    200: Array<TaskReadParticipant>;
};

export type GetMyTasksResponse = GetMyTasksResponses[keyof GetMyTasksResponses];

export type GetTasksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tasks/';
};

export type GetTasksResponses = {
    /**
     * Successful Response
     */
    200: Array<TaskRead>;
};

export type GetTasksResponse = GetTasksResponses[keyof GetTasksResponses];

export type CreateTaskData = {
    body: TaskCreate;
    path?: never;
    query?: never;
    url: '/tasks/';
};

export type CreateTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskError = CreateTaskErrors[keyof CreateTaskErrors];

export type CreateTaskResponses = {
    /**
     * Successful Response
     */
    200: TaskRead;
};

export type CreateTaskResponse = CreateTaskResponses[keyof CreateTaskResponses];

export type DeleteTaskData = {
    body?: never;
    path: {
        task_id: string;
    };
    query?: never;
    url: '/tasks/{task_id}';
};

export type DeleteTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTaskError = DeleteTaskErrors[keyof DeleteTaskErrors];

export type DeleteTaskResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTaskData = {
    body?: never;
    path: {
        task_id: string;
    };
    query?: never;
    url: '/tasks/{task_id}';
};

export type GetTaskErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskError = GetTaskErrors[keyof GetTaskErrors];

export type GetTaskResponses = {
    /**
     * Successful Response
     */
    200: TaskRead;
};

export type GetTaskResponse = GetTaskResponses[keyof GetTaskResponses];

export type GetSampleTaskData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tasks/sample';
};

export type GetSampleTaskResponses = {
    /**
     * Successful Response
     */
    200: TaskRead;
};

export type GetSampleTaskResponse = GetSampleTaskResponses[keyof GetSampleTaskResponses];

export type GetTaskResponsesData = {
    body?: never;
    path: {
        task_id: string;
    };
    query?: never;
    url: '/tasks/{task_id}/responses';
};

export type GetTaskResponsesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskResponsesError = GetTaskResponsesErrors[keyof GetTaskResponsesErrors];

export type GetTaskResponsesResponses = {
    /**
     * Successful Response
     */
    200: Array<TaskResponseRead>;
};

export type GetTaskResponsesResponse = GetTaskResponsesResponses[keyof GetTaskResponsesResponses];

export type CreateTaskResponseData = {
    body: TaskResponseCreate;
    path: {
        task_id: string;
    };
    query?: never;
    url: '/tasks/{task_id}/response';
};

export type CreateTaskResponseErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not found
     */
    404: ErrorResponse;
    /**
     * Task already completed
     */
    409: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskResponseError = CreateTaskResponseErrors[keyof CreateTaskResponseErrors];

export type CreateTaskResponseResponses = {
    /**
     * Successful Response
     */
    200: TaskResponseRead;
};

export type CreateTaskResponseResponse = CreateTaskResponseResponses[keyof CreateTaskResponseResponses];

export type GetTaskParticipantsData = {
    body?: never;
    path: {
        task_id: string;
    };
    query?: never;
    url: '/tasks/{task_id}/participants';
};

export type GetTaskParticipantsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskParticipantsError = GetTaskParticipantsErrors[keyof GetTaskParticipantsErrors];

export type GetTaskParticipantsResponses = {
    /**
     * Successful Response
     */
    200: Array<TaskParticipantRead>;
};

export type GetTaskParticipantsResponse = GetTaskParticipantsResponses[keyof GetTaskParticipantsResponses];

export type GetResponsesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/responses';
};

export type GetResponsesResponses = {
    /**
     * Successful Response
     */
    200: Array<TaskResponseRead>;
};

export type GetResponsesResponse = GetResponsesResponses[keyof GetResponsesResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};