// This file is auto-generated by @hey-api/openapi-ts

export type Agent = {
    id: string;
    name: string;
    type?: 'agent';
    endpoint: string;
    api_key: string;
    prompt: string;
};

export type Chat = {
    id: string | number;
    label?: Translations | null;
    optional?: boolean;
    type?: 'chat';
    agents?: Array<Agent>;
    order?: Array<string> | null;
    all_users: boolean;
    min_messages?: number;
};

export type ChatHistoryRead = {
    id: string;
    messages: Array<ChatMessageRead>;
};

export type ChatMessageRead = {
    message: string;
    id: string;
    chat: string;
    sender: string;
    timestamp: Date;
};

export type ComponentGroupInput = {
    /**
     * The number of columns used to display the children of this component
     */
    columns?: number;
    label?: Translations | null;
    components: Array<SingleChoice | MultiChoice | Slider | FreeText | Chat>;
};

export type ComponentGroupOutput = {
    /**
     * The number of columns used to display the children of this component
     */
    columns?: number;
    label?: Translations | null;
    components: Array<SingleChoice | MultiChoice | Slider | FreeText | Chat>;
};

export type ErrorResponse = {
    detail: string;
};

export type FreeText = {
    id: string | number;
    label?: Translations | null;
    optional?: boolean;
    type?: 'free_text';
    /**
     * The regular expression pattern that the user's input must match. `null` performs no matching.
     */
    regex?: string | null;
    /**
     * Prompt to be shown if the regex does not match
     */
    regex_prompt?: string | null;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type LoginRequired = {
    login_required: boolean;
};

export type MultiChoice = {
    id: string | number;
    label?: Translations | null;
    optional?: boolean;
    choices: Array<Translations>;
    /**
     * If `true`, choices are displayed in a random order to the user
     */
    shuffle?: boolean;
    type?: 'multi_choice';
    min_choices?: number;
    max_choices?: number;
};

export type RootModelInt = number;

export type RootModelListInt = Array<number>;

export type RootModelStr = string;

export type SingleChoice = {
    id: string | number;
    label?: Translations | null;
    optional?: boolean;
    choices: Array<Translations>;
    /**
     * If `true`, choices are displayed in a random order to the user
     */
    shuffle?: boolean;
    type?: 'single_choice';
};

export type Slider = {
    id: string | number;
    label?: Translations | null;
    optional?: boolean;
    type?: 'slider';
    steps: number;
    labels?: Array<Translations> | null;
};

export type TaskConfigInput = {
    name: Translations;
    description?: Translations | null;
    pages: Array<TaskPageInput>;
    login_required: boolean;
};

export type TaskConfigOutput = {
    name: Translations;
    description?: Translations | null;
    pages: Array<TaskPageOutput>;
    login_required: boolean;
};

export type TaskCreate = {
    config: TaskConfigInput;
};

export type TaskPageInput = {
    /**
     * The number of columns used to display the component groups
     */
    columns?: number;
    label?: Translations | string | null;
    component_groups: Array<ComponentGroupInput>;
};

export type TaskPageOutput = {
    /**
     * The number of columns used to display the component groups
     */
    columns?: number;
    label?: Translations | string | null;
    component_groups: Array<ComponentGroupOutput>;
};

export type TaskParticipantCreate = {
    user: string | null;
};

export type TaskParticipantRead = {
    task: string;
    user: string | null;
    completed: boolean;
};

export type TaskRead = {
    config: TaskConfigOutput;
    id?: string;
    login_required: boolean;
};

export type TaskReadParticipant = {
    config: TaskConfigOutput;
    id?: string;
    login_required: boolean;
    completed: boolean;
};

export type TaskResponse = {
    response: {
        [key: string]: RootModelInt | RootModelListInt | RootModelStr;
    };
    updated_timestamp?: Date;
    created_timestamp?: Date;
    task: string;
    user: string | null;
};

export type TaskResponseCreate = {
    response: {
        [key: string]: RootModelInt | RootModelListInt | RootModelStr;
    };
};

export type TaskResponseRead = {
    response: {
        [key: string]: RootModelInt | RootModelListInt | RootModelStr;
    };
    updated_timestamp?: Date;
    created_timestamp?: Date;
    task: string;
    user: string | null;
};

export type Translations = {
    languages: {
        [key: string]: unknown;
    };
    /**
     * Default language to display. Must must be in `languages`. Will display an arbitrary language if left `null`.
     */
    default?: string | null;
};

export type User = {
    id: string;
    attributes?: {
        [key: string]: unknown;
    };
    is_admin?: boolean;
};

export type UserCreate = {
    id: string;
    attributes?: {
        [key: string]: unknown;
    };
};

export type UserRead = {
    id: string;
    attributes?: {
        [key: string]: unknown;
    };
    is_admin?: boolean;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type GetChatData = {
    body?: never;
    path: {
        chat_id: string;
    };
    query?: never;
    url: '/chats/{chat_id}';
};

export type GetChatErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChatError = GetChatErrors[keyof GetChatErrors];

export type GetChatResponses = {
    /**
     * Successful Response
     */
    200: ChatHistoryRead;
};

export type GetChatResponse = GetChatResponses[keyof GetChatResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type GetUsersResponses = {
    /**
     * Successful Response
     */
    200: Array<UserRead>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type CreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/users';
};

export type CreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetMeResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type LoginRequiredData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/login-required';
};

export type LoginRequiredResponses = {
    /**
     * Successful Response
     */
    200: LoginRequired;
};

export type LoginRequiredResponse = LoginRequiredResponses[keyof LoginRequiredResponses];

export type GetUserData = {
    body?: never;
    path: {
        user_id: string | null;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type GetUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type GetUserResponsesData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}/responses';
};

export type GetUserResponsesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserResponsesError = GetUserResponsesErrors[keyof GetUserResponsesErrors];

export type GetUserResponsesResponses = {
    /**
     * Successful Response
     */
    200: Array<TaskResponse>;
};

export type GetUserResponsesResponse = GetUserResponsesResponses[keyof GetUserResponsesResponses];

export type GetMyTasksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/tasks';
};

export type GetMyTasksResponses = {
    /**
     * Successful Response
     */
    200: Array<TaskReadParticipant>;
};

export type GetMyTasksResponse = GetMyTasksResponses[keyof GetMyTasksResponses];

export type GetTasksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tasks/';
};

export type GetTasksResponses = {
    /**
     * Successful Response
     */
    200: Array<TaskRead>;
};

export type GetTasksResponse = GetTasksResponses[keyof GetTasksResponses];

export type CreateTaskData = {
    body: TaskCreate;
    path?: never;
    query?: never;
    url: '/tasks/';
};

export type CreateTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskError = CreateTaskErrors[keyof CreateTaskErrors];

export type CreateTaskResponses = {
    /**
     * Successful Response
     */
    200: TaskRead;
};

export type CreateTaskResponse = CreateTaskResponses[keyof CreateTaskResponses];

export type DeleteTaskData = {
    body?: never;
    path: {
        task_id: string;
    };
    query?: never;
    url: '/tasks/{task_id}';
};

export type DeleteTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTaskError = DeleteTaskErrors[keyof DeleteTaskErrors];

export type DeleteTaskResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTaskData = {
    body?: never;
    path: {
        task_id: string;
    };
    query?: never;
    url: '/tasks/{task_id}';
};

export type GetTaskErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskError = GetTaskErrors[keyof GetTaskErrors];

export type GetTaskResponses = {
    /**
     * Successful Response
     */
    200: TaskRead;
};

export type GetTaskResponse = GetTaskResponses[keyof GetTaskResponses];

export type GetSampleTaskData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tasks/sample';
};

export type GetSampleTaskResponses = {
    /**
     * Successful Response
     */
    200: TaskRead;
};

export type GetSampleTaskResponse = GetSampleTaskResponses[keyof GetSampleTaskResponses];

export type GetTaskResponsesData = {
    body?: never;
    path: {
        task_id: string;
    };
    query?: never;
    url: '/tasks/{task_id}/responses';
};

export type GetTaskResponsesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskResponsesError = GetTaskResponsesErrors[keyof GetTaskResponsesErrors];

export type GetTaskResponsesResponses = {
    /**
     * Successful Response
     */
    200: Array<TaskResponseRead>;
};

export type GetTaskResponsesResponse = GetTaskResponsesResponses[keyof GetTaskResponsesResponses];

export type CreateTaskResponseData = {
    body: TaskResponseCreate;
    path: {
        task_id: string;
    };
    query?: never;
    url: '/tasks/{task_id}/response';
};

export type CreateTaskResponseErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not found
     */
    404: ErrorResponse;
    /**
     * Task already completed
     */
    409: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskResponseError = CreateTaskResponseErrors[keyof CreateTaskResponseErrors];

export type CreateTaskResponseResponses = {
    /**
     * Successful Response
     */
    200: TaskResponseRead;
};

export type CreateTaskResponseResponse = CreateTaskResponseResponses[keyof CreateTaskResponseResponses];

export type GetTaskParticipantsData = {
    body?: never;
    path: {
        task_id: string;
    };
    query?: never;
    url: '/tasks/{task_id}/participants';
};

export type GetTaskParticipantsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTaskParticipantsError = GetTaskParticipantsErrors[keyof GetTaskParticipantsErrors];

export type GetTaskParticipantsResponses = {
    /**
     * Successful Response
     */
    200: Array<TaskParticipantRead>;
};

export type GetTaskParticipantsResponse = GetTaskParticipantsResponses[keyof GetTaskParticipantsResponses];

export type CreateTaskParticipantData = {
    body: TaskParticipantCreate;
    path: {
        task_id: string;
    };
    query?: never;
    url: '/tasks/{task_id}/participants';
};

export type CreateTaskParticipantErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskParticipantError = CreateTaskParticipantErrors[keyof CreateTaskParticipantErrors];

export type CreateTaskParticipantResponses = {
    /**
     * Successful Response
     */
    200: TaskParticipantRead;
};

export type CreateTaskParticipantResponse = CreateTaskParticipantResponses[keyof CreateTaskParticipantResponses];

export type GetResponsesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/responses';
};

export type GetResponsesResponses = {
    /**
     * Successful Response
     */
    200: Array<TaskResponseRead>;
};

export type GetResponsesResponse = GetResponsesResponses[keyof GetResponsesResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};